services:

  postgres:
    container_name: webhook-base-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: base
      POSTGRES_PASSWORD: base
      POSTGRES_DB: base
    networks:
      - base
    volumes:
      - postgres_data:/var/lib/postgresql/data

  base-app:
    container_name: base-app
    build: .
    volumes:
      - ./:/srv/Essaie_Webhook
    ports:
      - "8000:8000"
    command: /bin/bash
    stdin_open: true
    tty: true
    networks:
      - base
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  base:
    driver: bridge
