# Generated by Django 5.2 on 2025-05-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entraineur",
            fields=[
                ("id_En", models.IntegerField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("experience", models.IntegerField(help_text="Années d'expérience")),
                ("nationalite", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Joueur",
            fields=[
                ("id_J", models.IntegerField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "poste",
                    models.CharField(
                        choices=[
                            ("GK", "Gardien"),
                            ("DEF", "Défenseur"),
                            ("MID", "Milieu"),
                            ("ATT", "Attaquant"),
                        ],
                        default="MID",
                        max_length=3,
                    ),
                ),
                ("nationalite", models.CharField(max_length=50)),
                (
                    "pied_fort",
                    models.CharField(
                        choices=[
                            ("D", "Droit"),
                            ("G", "Gauche"),
                            ("O", "Ousmane Dembélé"),
                        ],
                        default="D",
                        max_length=1,
                    ),
                ),
                ("nombre_but", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Equipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("stade", models.CharField(max_length=100)),
                (
                    "entraineur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Football.entraineur",
                    ),
                ),
                ("joueurs", models.ManyToManyField(to="Football.joueur")),
            ],
        ),
    ]
